<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
	<LangVersion>preview</LangVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>CC98</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platform>x64</Platform>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
	  <WindowsSdkPackageVersion>10.0.26100.81</WindowsSdkPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\cc98.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\cc98.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\cc98.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\cc98.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\cc98.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\cc98.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\cc98.altform-unplated_targetsize-24.png" />
    <Content Remove="Assets\cc98.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\cc98.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\cc98.altform-unplated_targetsize-48.png" />
    <Content Remove="Assets\cc98.targetsize-16.png" />
    <Content Remove="Assets\cc98.targetsize-24.png" />
    <Content Remove="Assets\cc98.targetsize-256.png" />
    <Content Remove="Assets\cc98.targetsize-32.png" />
    <Content Remove="Assets\cc98.targetsize-48.png" />
    <Content Remove="Assets\LargeTile.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\LargeTile.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\LargeTile.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\LargeTile.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\LargeTile.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\LargeTile.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\LargeTile.altform-unplated_targetsize-24.png" />
    <Content Remove="Assets\LargeTile.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\LargeTile.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\LargeTile.altform-unplated_targetsize-48.png" />
    <Content Remove="Assets\LargeTile.targetsize-16.png" />
    <Content Remove="Assets\LargeTile.targetsize-24.png" />
    <Content Remove="Assets\LargeTile.targetsize-256.png" />
    <Content Remove="Assets\LargeTile.targetsize-32.png" />
    <Content Remove="Assets\LargeTile.targetsize-48.png" />
    <Content Remove="Assets\SmallTile.scale-100.png" />
    <Content Remove="Assets\SmallTile.scale-125.png" />
    <Content Remove="Assets\SmallTile.scale-150.png" />
    <Content Remove="Assets\SmallTile.scale-200.png" />
    <Content Remove="Assets\Square150x150Logo.scale-100.png" />
    <Content Remove="Assets\Square150x150Logo.scale-125.png" />
    <Content Remove="Assets\Square150x150Logo.scale-150.png" />
    <Content Remove="Assets\Square150x150Logo.scale-400.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-16.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-24.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-256.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-32.png" />
    <Content Remove="Assets\Square44x44Logo.targetsize-48.png" />
    <Content Remove="Assets\SquareLogo.altform-lightunplated_targetsize-16.png" />
    <Content Remove="Assets\SquareLogo.altform-lightunplated_targetsize-24.png" />
    <Content Remove="Assets\SquareLogo.altform-lightunplated_targetsize-256.png" />
    <Content Remove="Assets\SquareLogo.altform-lightunplated_targetsize-32.png" />
    <Content Remove="Assets\SquareLogo.altform-lightunplated_targetsize-48.png" />
    <Content Remove="Assets\SquareLogo.altform-unplated_targetsize-16.png" />
    <Content Remove="Assets\SquareLogo.altform-unplated_targetsize-24.png" />
    <Content Remove="Assets\SquareLogo.altform-unplated_targetsize-256.png" />
    <Content Remove="Assets\SquareLogo.altform-unplated_targetsize-32.png" />
    <Content Remove="Assets\SquareLogo.altform-unplated_targetsize-48.png" />
    <Content Remove="Assets\SquareLogo.targetsize-16.png" />
    <Content Remove="Assets\SquareLogo.targetsize-24.png" />
    <Content Remove="Assets\SquareLogo.targetsize-256.png" />
    <Content Remove="Assets\SquareLogo.targetsize-32.png" />
    <Content Remove="Assets\SquareLogo.targetsize-48.png" />
    <Content Remove="Assets\StoreLogo.scale-100.png" />
    <Content Remove="Assets\StoreLogo.scale-125.png" />
    <Content Remove="Assets\StoreLogo.scale-150.png" />
    <Content Remove="Assets\StoreLogo.scale-200.png" />
    <Content Remove="Assets\StoreLogo.scale-400.png" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\cc98.png" />
    <None Remove="Assets\cc98.scale-100.png" />
    <None Remove="Assets\cc98.scale-125.png" />
    <None Remove="Assets\cc98.scale-150.png" />
    <None Remove="Assets\cc98.scale-200.png" />
    <None Remove="Assets\cc98.scale-400.png" />
    <None Remove="Assets\LargeTile.scale-100.png" />
    <None Remove="Assets\LargeTile.scale-125.png" />
    <None Remove="Assets\LargeTile.scale-150.png" />
    <None Remove="Assets\LargeTile.scale-200.png" />
    <None Remove="Assets\LargeTile.scale-400.png" />
    <None Remove="Assets\LockScreenLogo.scale-100.png" />
    <None Remove="Assets\LockScreenLogo.scale-125.png" />
    <None Remove="Assets\LockScreenLogo.scale-150.png" />
    <None Remove="Assets\LockScreenLogo.scale-400.png" />
    <None Remove="Assets\SmallTile.scale-400.png" />
    <None Remove="Assets\SplashScreen.scale-100.png" />
    <None Remove="Assets\SplashScreen.scale-125.png" />
    <None Remove="Assets\SplashScreen.scale-150.png" />
    <None Remove="Assets\SplashScreen.scale-400.png" />
    <None Remove="Assets\Square44x44Logo.scale-100.png" />
    <None Remove="Assets\Square44x44Logo.scale-125.png" />
    <None Remove="Assets\Square44x44Logo.scale-150.png" />
    <None Remove="Assets\Square44x44Logo.scale-400.png" />
    <None Remove="Assets\SquareLogo.scale-100.png" />
    <None Remove="Assets\SquareLogo.scale-125.png" />
    <None Remove="Assets\SquareLogo.scale-150.png" />
    <None Remove="Assets\SquareLogo.scale-200.png" />
    <None Remove="Assets\SquareLogo.scale-400.png" />
    <None Remove="Assets\Wide310x150Logo.scale-100.png" />
    <None Remove="Assets\Wide310x150Logo.scale-125.png" />
    <None Remove="Assets\Wide310x150Logo.scale-150.png" />
    <None Remove="Assets\Wide310x150Logo.scale-400.png" />
    <None Remove="Board.xaml" />
    <None Remove="CC98 Desktop_1.0.5.0_x64_Debug.cer" />
    <None Remove="CC98 Desktop_1.0.5预览体验（x64）.zip" />
    <None Remove="CC98 Desktop_1.0.6.0_x64_Debug.cer" />
    <None Remove="Discover.xaml" />
    <None Remove="Focus.xaml" />
    <None Remove="Friend.xaml" />
    <None Remove="Game.xaml" />
    <None Remove="Index.xaml" />
    <None Remove="InfoFlower.xaml" />
    <None Remove="login.xaml" />
    <None Remove="MediaViewer.xaml" />
    <None Remove="Message.xaml" />
    <None Remove="Post.xaml" />
    <None Remove="Profile.xaml" />
    <None Remove="Search.xaml" />
    <None Remove="Section.xaml" />
    <None Remove="Setting.xaml" />
    <None Remove="Themes\Generic.xaml" />
    <None Remove="Topic.xaml" />
    <None Remove="UBBRichTextBlock.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
	<TrimmerRootAssembly Include="CommunityToolkit.WinUI.UI.Controls.Markdown" />
	<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.Shimmer" Version="0.1.260203-build.2518" />
    <PackageReference Include="CommunityToolkit.Labs.WinUI.Ribbon" Version="0.1.250721-build.2183" />
    <PackageReference Include="CommunityToolkit.Labs.WinUI.TokenView" Version="0.1.250721-build.2183" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.ColorPicker" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.Markdown" Version="7.1.2" />
    <PackageReference Include="CSharpMath.SkiaSharp" Version="0.5.1" />
    <PackageReference Include="DevWinUI" Version="9.8.1" />
    <PackageReference Include="DevWinUI.Controls" Version="9.8.1" />
    <PackageReference Include="Duende.IdentityModel.OidcClient" Version="7.0.0" />
    <PackageReference Include="FluentIcons.WinUI" Version="2.0.316" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7175" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageReference Include="SkiaSharp.Views.WinUI" Version="3.119.2" />
  </ItemGroup>
	
  <ItemGroup>
	
    <Page Update="UBBRichTextBlock.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Profile.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Topic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Topic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Index.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="InfoFlower.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Game.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Focus.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Search.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Friend.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="MediaViewer.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Chat.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Message.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Favorite.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Post.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="login.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Setting.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Board.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Discover.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Section.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Notice.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Themes\Generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="SmartImage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <WebView2DispatchAdapterNamespace>CC98</WebView2DispatchAdapterNamespace>
  </PropertyGroup>

  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>

  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun>True</PublishReadyToRun>
    <DefaultLanguage>zh-cn</DefaultLanguage>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateKeyFile>CC98 Desktop_TemporaryKey.pfx</PackageCertificateKeyFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Never</AppxBundle>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <AppxPackageDir>C:\Users\Ansherly\Downloads\</AppxPackageDir>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
    <PublishAot>True</PublishAot>
	<PublishTrimmed>True</PublishTrimmed>
	<TrimMode>full</TrimMode>
    <ApplicationIcon>Assets\cc98.ico</ApplicationIcon>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <Optimize>True</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>True</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <Optimize>True</Optimize>
  </PropertyGroup>
</Project>